# docker build -f Containerfile -t docker.io/lolei/irssi:$TAG .
# docker push docker.io/lolei/irssi:$TAG

FROM docker.io/irssi:1.2.3

USER root

RUN apt update
RUN apt install screen vim -y

USER user

ENTRYPOINT ["bash", "-c", "while true; do echo 'looping endlessly...'; sleep 3600; done"]
